build-project:
  tags:
    - java
    - openjdk
    - shared
  stage: build
  script:
    - cd test
    - javac gitlab/ci/CIJupiterRunner.java

run-junit-tests:
  tags:
    - java
    - openjdk
    - shared
  stage: test
  script: 
    - cd test
    - java gitlab/ci/CIJupiterRunner
    
pages:
  tags:
    - java
    - openjdk
    - shared
  stage: deploy
  script:
    - echo "Generating gameboj website"
  artifacts:
    paths: 
    - website/html
    - website/css
    - website/js
    