build-project:
  tags:
    - java
    - openjdk
    - shared
  stage: build
  script:
    - echo "Building project"

run-junit-tests:
  tags:
    - java
    - openjdk
    - shared
  stage: test
  script: 
    - cd test
    - javac gitlab/ci/CIJupiterRunner.java
    - java gitlab/ci/CIJupiterRunner
    