image: openjdk

build-project:
  tags:
    - gitlab-org
  stage: build
  script:
    - echo "Building project"

run-junit-tests:
  tags:
    - gitlab-org
  stage: test
  script: 
    - cd test
    - javac gitlab/ci/CIJupiterRunner.java
    - java gitlab/ci/CIJupiterRunner
 
test-coverage:
  tags:
    - gitlab-org
  stage: test
  script:
    - echo "Test coverage"
  artifacts:
    paths:
      - coverage/
  
deploy_review:
  tags:
    - gitlab-org
  stage: deploy
  script:
    - echo "Deploying to review environment"
  environment:
    name: review
    url: https://dave_and_chris.gitlab.io/gameboj/review.html

deploy_production:
  tags:
    - gitlab-org
  stage: deploy
  script:
    - echo "Deploying to review environment"
  environment:
    name: production
    url: https://dave_and_chris.gitlab.io/gameboj/production.html