run-junit-tests:
  tags:
    - java
    - openjdk
    - shared
  stage: test
  script: 
    - cd test
    - ls
    - javac gitlab/ci/CIJupiterRunner.java
    - ls
    - java gitlab/ci/CIJupiterRunner
    