image: openjdk

build-project:
  tags:
    - gitlab-org
  stage: build
  script:
    - echo "Building project"

run-junit-tests:
  tags:
    - gitlab-org
  stage: test
  script: 
    - cd test
    - javac gitlab/ci/CIJupiterRunner.java
    - java gitlab/ci/CIJupiterRunner
 
test-coverage:
  tags:
    - gitlab-org
  stage: test
  script:
    - echo "Test coverage"
  artifacts:
    paths:
      - coverage/
  
