run-junit-tests:
  tags:
    - java
    - openjdk
    - shared
  stage: test
  script: 
    - cd test/gitlab/ci
    - ls
    - rm -rf CIJupiterRunner.class
    - ls
    - javac CIJupiterRunner.java
    - ls
    - java CIJupiterRunner
    