image: openjdk

build-project:
  tags:
    - gitlab-org
  stage: build
  script:
    - echo "Building project"

run-junit-tests:
  tags:
    - gitlab-org
  stage: test
  script: 
    - cd test
    - javac gitlab/ci/CIJupiterRunner.java
    - java gitlab/ci/CIJupiterRunner
  
pages:
  tags:
    - gitlab-org
  stage: deploy
  script:  
    - echo "Deploying website"
  artifacts:
    paths:
    - public
  only: 
  - master
